name: Test Fail Job

on:
  push:
    branches:
      - main

jobs:
  fail-job-example:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout
        uses: actions/checkout@v3

      # Normal step
      - name: Say Hello
        run: echo "This is a normal step"

      # Step that fails intentionally
      - name: Fail the job
        run: |
          echo "This step will fail intentionally"
          exit 1
